openapi: 3.0.0
info:
  title: CULQI API
  version: '1.0'
  description: |-
    # Introducción
    La API de [Culqi](http://culqi.com/) está construido bajo los estándares de **REST**. Es decir, nuestra API posee URLs orientada a recursos, y hace uso de los [códigos de respuesta HTTP](https://httpstatuses.com/) para indicar los posibles errores en el API. Es importante indicar que se encuentra implementada una autenticación HTTP (<em>Bearer Token</em>), solicitada en cada petición. A<demás, soportamos las solicitudes HTTP de origen cruzado (CORS), permitiendo que tu sitio y Culqi puedan interactuar de manera segura mediante nuestra API desde una aplicación cliente (aunque NUNCA deberías exponer tu Llave Secreta en el código de la aplicación web cliente). Por otro lado, un objeto JSON es retornado en cada una las peticiones hacia el API, incluyendo los errores. Adicionalmente nuestras bibliotecas convierten las respuestas en objetos específicos para cada lenguaje soportado.

    Finalmente, para que puedas comenzar a experimentar con nuestra API, todas las cuentas registradas en Culqi poseen llaves para el entorno de pruebas (Regístrate y obtén tus llaves) y el entorno de producción. Usando las llaves de prueba las transacciones nunca pasan por las redes bancarias y no tienen ningún costo. (¡Recuerda usar tarjetas de prueba, no tarjetas reales al probar!).

    This API is documented in **OpenAPI format** and is based on
    [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
    It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
    tool and [ReDoc](https://github.com/Redocly/redoc) documentation. In addition to standard
    OpenAPI syntax we use a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md).
servers:
  - url: 'https://api.culqi.com'
tags:
  - name: Tokens
    description: |-
      **Tokenización** es el proceso que utiliza Culqi para capturar de manera segura datos sensibles de tarjetas de crédito y débito directamente desde el navegador del cliente. Un token representa la información de la tarjeta y es devuelto a tus servidores para que puedas utilizarlo a través de [Culqi Checkout](https://docs.culqi.com/#/pagos/checkout), [Culqi.JS](https://docs.culqi.com/#/pagos/js) o nuestras bibliotecas para móviles ([iOS](https://docs.culqi.com/#/pagos/ios) y [Android](https://docs.culqi.com/#/pagos/android)). Este método nos asegura que ningún dato de tarjeta toque tus servidores y permite que la integración cumple con la normativa **PCI DSS**.
      </br> </br>
      Si no deseas hacer uso de los métodos de tokenización disponibles, también podrías crear tokens utilizando la API y tu llave pública. Pero en este caso recuerda que tu empresa será la responsable de cualquier procedimiento requerido por la normativa PCI DSS, como por ejemplo el [siguiente autocuestionario](https://www.pcisecuritystandards.org/documents/SAQ_D_v3_Merchant.pdf). A diferencia de Culqi Checkout, Culqi.JS y los SDKs para móviles, la información de tu cliente no sería enviada directamente a Culqi así que no podríamos determinar si manejas o guardas esta información con seguridad.
      </br>
      - Los tokens tienen un tiempo de expiración de 5 minutos por lo que no pueden ser guardados y utilizados más de una vez. Para hacerlos permanentes y generar cargos posteriores o recurrentes, debes [crear un cliente](#tag/Clientes/operation/post-v2-customers) y posteriormente [crear una tarjeta]().
  - name: Cargos
    description: 'Para realizar un cargo a una tarjeta de débito o crédito debes crear un objeto cargo. Adicionalmente puedes consultar, devolver un cargo en particular o listar tu historial de cargos en base a los filtros que desees. Todos los cargos están identificados por un ID.'
  - name: Devoluciones
    description: Una devolución te permite devolver un cargo que ha sido creado previamente y que aún no ha sido devuelto en su totalidad. Los fondos serán devueltos a la tarjeta de crédito o débito que se ha realizado el cargo.
  - name: Clientes
    description: 'El recurso cliente te permite guardar la información de tus clientes para realizarles cargos recurrentes o posteriores. La API de Culqi permite crear, eliminar y actualizar los datos de tus clientes. Adicionalmente podrás consultar los datos de un cliente en particular o listar a todos tus clientes en base a los filtros que desees.'
paths:
  /v2/tokens:
    post:
      tags:
        - Tokens
      summary: Crear Token
      operationId: post-v2-tokens
      description: |-
        Crear tokens te permitirá obtener información de la tarjeta y utilizarla para crear un cargo o crear una tarjeta.
        - Si desarrollas una pagina web deberías crear token utilizando Culqi Checkout o CulqiJS
        - Si desarrollas una aplicación móvil deberías crear token utilizando nuestros SDKs para móviles (iOS o Android)
        - Si deseas crear el token de manera directa con el API de Culqi debes llenar el siguiente autocuestionario.
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer << llave_publica >>
          in: header
          name: Authorization
          required: true
          description: Llave publica
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  card_number: '4111111111111111'
                  cvv: '123'
                  expiration_month: '09'
                  expiration_year: '2020'
                  email: richard@piedpiper.com
              properties:
                card_number:
                  type: string
                  minLength: 13
                  maxLength: 16
                  description: Número de tarjeta.
                  example: '4111111111111111'
                cvv:
                  type: string
                  minLength: 1
                  description: CVV de la tarjeta.
                  example: '123'
                expiration_month:
                  type: string
                  minLength: 1
                  maxLength: 2
                  example: '09'
                  description: Mes de expiración de la tarjeta.
                expiration_year:
                  type: string
                  description: Año de expiración de la tarjeta.
                  minLength: 4
                  maxLength: 4
                  example: '2020'
                email:
                  type: string
                  description: Dirección de correo electrónico del cliente.
                  minLength: 5
                  maxLength: 50
                  example: ichard@piedpiper.com
                metadata:
                  type: object
                  description: Informacion adicional que se quiere enviar del token.
                  example:
                    dni: '5831543'
              required:
                - card_number
                - cvv
                - expiration_month
                - expiration_year
                - email
            examples:
              ejemplo 1:
                value:
                  card_number: '4111111111111111'
                  cvv: '123'
                  expiration_month: '09'
                  expiration_year: '2020'
                  email: ichard@piedpiper.com
                  metadata:
                    dni: '5831543'
      responses:
        '201':
          description: La petición exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                ejemplo 1:
                  value:
                    object: token
                    id: tkn_live_0CjjdWhFpEAZlxlz
                    type: card
                    email: richard@piedpiper.com
                    creation_date: 1476132639
                    card_number: 442328******1214
                    last_four: '1214'
                    active: true
                    iin:
                      object: iin
                      bin: '442328'
                      card_brand: Visa
                      card_type: credito
                      card_category: platinum
                      issuer:
                        name: Silicon Valley Bank
                        country: United States
                        country_code: US
                        website: 'https://www.svb.com'
                        phone_number: +1.800.774.7390
                      installments_allowed:
                        - 2
                        - 4
                        - 8
                        - 12
                        - 24
                        - 36
                    client:
                      ip: 72.229.28.185
                      ip_country: United States
                      ip_country_code: US
                      browser: Google Chrome 56.0.2924.87
                      device_fingerprint: 6rITdVTYkWfOrss8
                      device_type: escritorio
                    metadata:
                      dni: '5831543'
    get:
      tags:
        - Tokens
      summary: Listar Tokens
      operationId: get-v2-tokens
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                ejemplo 1:
                  value:
                    data: []
                    paging:
                      previous: null
                      next: null
                      cursors:
                        before: null
                        after: null
      description: 'Listar tokens te permitirá obtener una serie de tokens existentes. De acuerdo a los filtros que uses los tokens serán ordenados de acuerdo a la fecha de creación, siendo el primero el más reciente.'
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
        - schema:
            type: string
            example: '1476132639'
          in: query
          name: creation_date
          description: Fecha del token en UNIX Timestamp.
        - schema:
            type: string
          in: query
          name: creation_date_to
          description: Número de tarjeta.
        - schema:
            type: string
            enum:
              - Visa
              - Mastercard
              - Amex
              - Diner
          in: query
          name: card_brand
          description: Marca de la tarjeta.
        - schema:
            type: string
            enum:
              - credito
              - debito
              - prepagada
          in: query
          name: card_type
          description: Tipo de tarjeta.
        - schema:
            type: string
            enum:
              - escritorio
              - movil
              - tablet
          in: query
          name: device_type
          description: Tipo de dispositivo.
        - schema:
            type: string
            minLength: 6
            maxLength: 6
            example: '411111'
          in: query
          name: bin
          description: Primeros seis dígitos de la tarjeta expresado en formato ISO/IEC 7812.
        - schema:
            type: string
            example: PE
          in: query
          name: country_code
          description: 'Código del país, en formato ISO-3166 (Alfa 2).'
        - schema:
            type: string
            example: '50'
            minLength: 1
            maxLength: 100
          in: query
          name: limit
          description: Cantidad exacta de tokens que se quieren listar.
        - schema:
            type: string
            minLength: 25
            maxLength: 25
            example: tkn_live_7lYOtONQ9LxcgJUW
          in: query
          name: before
          description: El ID del token desde donde se quiere traer los resultados anteriores. No inclusivo.
        - schema:
            type: string
            example: tkn_live_7lYOtOMM6LxcgJUW
            minLength: 25
            maxLength: 25
          in: query
          name: after
          description: El ID del token desde donde se quiere traer los resultados siguientes. No inclusivo.
      requestBody:
        content:
          application/json:
            schema:
              type: object
  '/v2/tokens/{id}':
    get:
      tags:
        - Tokens
      summary: Consultar Token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                ejemplo 1:
                  value:
                    object: token
                    id: tkn_live_701ug3CDNJOAt5Q6
                    type: card
                    creation_date: 1486686216000
                    card_number: 411111******1111
                    last_four: '1111'
                    active: false
                    iin:
                      object: iin
                      bin: '411111'
                      card_brand: Visa
                      card_type: credit
                      card_category: Clásica
                      issuer:
                        name: 'JPMORGAN CHASE BANK, N.A.'
                        country: United States
                        country_code: PE
                        website: null
                        phone_number: null
                      installments_allowed:
                        - 2
                        - 4
                        - 6
                        - 8
                        - 10
                        - 12
                    client:
                      ip: 190.235.231.153
                      ip_country: Perú
                      ip_country_code: PE
                      browser: null
                      device_fingerprint: null
                      device_type: null
      operationId: get-v2-cc
      description: Consultar el detalle de un token utilizando su respectivo ID te permitirá obtener como respuesta el objeto token solicitado. Si la petición es inválida te devolveremos un error.
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
    parameters:
      - schema:
          type: string
          example: tkn_live_LVNpj300apa78Pjq
          minLength: 25
          maxLength: 25
        name: id
        in: path
        required: true
        description: ID del token a consultar.
    patch:
      tags:
        - Tokens
      summary: Actualizar Token
      operationId: patch-v2-tokens-id
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                ejemplo 1:
                  value:
                    data: []
                    paging:
                      previous: null
                      next: null
                      cursors:
                        before: null
                        after: null
      description: Actualizar un token te permitirá agregar o reemplazar información a los valores de la metadata que enviaste a la hora de crearla. Cualquier parámetro o valor no provisto será omitido en los valores de la metadata.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  metadata:
                    order_id: '0001'
              properties:
                metadata:
                  type: object
                  description: Informacion adicional que se quiere enviar del token.
                  example:
                    dni: '5831543'
                    cliente_id: 259
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
  /v2/charges:
    post:
      tags:
        - Cargos
      summary: Crear cargo
      operationId: post-v2-charges
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    duplicated: false
                    object: charge
                    id: chr_live_kEazTaQBDtzNdwFr
                    amount: 10000
                    amount_refunded: 0
                    current_amount: 10000
                    installments: 0
                    installments_amount: null
                    currency: PEN
                    email: null
                    description: null
                    source:
                      object: token
                      id: tkn_live_701ug3CDNJOAt5Q6
                      type: card
                      creation_date: 1487021247000
                      card_number: 411111******1111
                      last_four: '1111'
                      active: true
                      iin:
                        object: iin
                        bin: '411111'
                        card_brand: Visa
                        card_type: credit
                        card_category: Clásica
                        issuer:
                          name: 'JPMORGAN CHASE BANK, N.A.'
                          country: United States
                          country_code: PE
                          website: null
                          phone_number: null
                        installments_allowed:
                          - 2
                          - 4
                          - 6
                          - 8
                          - 10
                          - 12
                      client:
                        ip: 190.235.231.153
                        ip_country: Perú
                        ip_country_code: PE
                        browser: null
                        device_fingerprint: null
                        device_type: null
                    fraud_score: null
                    antifraud_details:
                      country_code: null
                      first_name: null
                      last_name: null
                      address_city: null
                      address: null
                      email: richard@piedpiper.com
                      phone: null
                      object: client
                    date: 1487021262000
                    reference_code: kwd3glvhbs
                    fee: null
                    fee_details:
                      - type: comision_porcentual
                        amount: 375
                        taxes: 68
                        total_amount: 443
                        currency_code: PEN
                        object: fee
                    net_amount: 9557
                    response_code: venta_exitosa
                    merchant_message: La operación de venta ha sido autorizada exitosamente
                    user_message: Su compra ha sido exitosa.
                    device_ip: 190.235.231.153
                    device_country: null
                    country_ip: null
                    product: token
                    state: Exitosa
                    metadata: null
      description: 'Para realizar un cobro a una tarjeta de débito o crédito es necesario crear un cargo usando un Token o una Tarjeta. Si utilizas tu llave secreta de integración no se realizarán cargos reales, a diferencia del entorno de producción donde enviamos tu petición a los bancos y marcas procesadoras.'
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  amount: '10000'
                  currency_code: PEN
                  email: richard@piedpiper.com
                  source_id: tkn_live_0CjjdWhFpEAZlxlz
              properties:
                amount:
                  type: integer
                  description: Monto del cargo. Sin punto decimal.
                  example: 100.00 serían 10000
                  maximum: 999900
                  minimum: 300
                currency_code:
                  type: string
                  minLength: 1
                  description: Código de la moneda en tres letras (Formato ISO 4217).
                  enum:
                    - PEN
                    - USD
                email:
                  type: string
                  minLength: 5
                  description: Correo electrónico del cliente.
                  example: richard@piedpiper.com
                  maxLength: 50
                source_id:
                  type: string
                  description: ID del objeto Token u objeto Tarjeta que se va usar para realizar el cargo.
                  example: 'tkn_live_701ug3CDNJOAt5Q6, crd_live_TWsfemI22ypplGK6'
                  minLength: 25
                  maxLength: 25
                capture:
                  type: boolean
                  description: Indica si se va realizar la captura automática de la tarjeta. Si no se considera por defecto tiene el valor de "true"
                description:
                  type: string
                  description: Descripción del cargo a realizarse.
                  example: Prueba
                  minLength: 5
                  maxLength: 80
                installments:
                  type: string
                  description: Cantidad de cuotas que se van a aplicar al pago. Estas dependen de las cuotas aceptadas por el objeto token.
                  minLength: 2
                  maxLength: 48
                  example: 2
                metadata:
                  type: object
                  description: Informacion adicional que se quiere enviar del cargo
                  example:
                    dni: '70202170'
                antifraud_details:
                  type: object
                  description: 'Datos de la persona que realiza la compra, para detectar posibles fraudes.'
              required:
                - amount
                - currency_code
                - email
                - source_id
            examples:
              example-1:
                value:
                  amount: '10000'
                  currency_code: PEN
                  email: richard@piedpiper.com
                  source_id: tkn_live_0CjjdWhFpEAZlxlz
    get:
      tags:
        - Cargos
      summary: Listar Cargos
      operationId: get-v2-charges
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    data:
                      - ...
                    paging:
                      previous: 'https://api.culqi.com/v2/charges?limit=50&before=chr_test_ 3nKwGp5EGMA8fxaW'
                      next: 'https://api.culqi.com/v2/charges?limit=50&after=chr_test_3nKwG p5EGMA8fxaW'
                      cursors:
                        before: chr_test_3nKwGp5EGMA8fxaW
                        after: chr_test_3nKwGp5EGMA8fxaW
      description: 'Listar cargos te permitirá obtener una serie de cargos existentes, de acuerdo a los filtros que uses. Los cargos serán ordenados de acuerdo a su fecha de creación, siendo el primero el más reciente.'
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
        - schema:
            type: string
            minLength: 300
            maxLength: 999900
            example: 500.00 sería 50000
          in: query
          name: amount
          description: Monto de los cargos en céntimos.
        - schema:
            type: string
            minLength: 300
            maxLength: 999900
            example: 100.00 sería 10000
          in: query
          name: min_amount
          description: Monto mínimo de los cargos en céntimos.
        - schema:
            type: string
            example: 100.00 sería 10000
            maxLength: 999900
            minLength: 300
          in: query
          name: max_amount
          description: Monto máximo de los cargos en céntimos.
        - schema:
            type: string
            minLength: 2
            maxLength: 48
            example: '4'
          in: query
          name: installments
          description: Cantidad de cuotas que se aplicaron al Cargo.
        - schema:
            type: string
            example: '8'
            minLength: 2
            maxLength: 48
          in: query
          name: min_installments
          description: Cantidad mínima de cuotas que se aplicaron al Cargo.
        - schema:
            type: string
            example: '48'
            minLength: 2
            maxLength: 48
          in: query
          name: max_installments
          description: Cantidad máxima de cuotas que se aplicaron al Cargo.
        - schema:
            type: string
          in: query
          name: currency_code
          description: Código de la moneda en la que se realizaron los cargos cargo en formato ISO 4217.
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              example-1: {}
        description: ''
  '/v2/charges/{id}':
    parameters:
      - schema:
          type: string
          example: chr_live_7VUwCneoG1XtLeS7
          minLength: 25
          maxLength: 25
        name: id
        in: path
        required: true
        description: ID del cargo.
    get:
      summary: Consultar Cargo
      tags:
        - Cargos
      responses:
        '200':
          description: La petición fue exitosa.
      operationId: get-v2-charges-id
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
      description: 'Consultar el detalle de un cargo utilizando el ID devuelto en la petición de creación, esto te permitirá obtener como respuesta todos los parámetros del objeto cargo.'
    patch:
      summary: Actualizar Cargo
      operationId: patch-v2-charges-id
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      dni:
                        type: string
                        minLength: 1
                    required:
                      - dni
                required:
                  - metadata
                x-examples:
                  example-1:
                    metadata:
                      dni: '71702323'
              examples:
                example-1:
                  value:
                    metadata:
                      dni: '71702323'
      description: Actualizar un cargo te permitirá agregar o reemplazar información a los valores de la metadata que enviaste a la hora de crear un cargo. Cualquier parámetro o valor no provisto será omitido en la el valores de la metadata.
      parameters:
        - schema:
            type: string
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada
          required: true
      tags:
        - Cargos
  '/v2/charges/{id}/capture':
    parameters:
      - schema:
          type: string
          minLength: 25
          maxLength: 25
          example: chr_live_7VUwCneoG1XtLeS7
        name: id
        in: path
        required: true
        description: ID del cargo a capturar.
    post:
      summary: Capturar Cargos
      operationId: post-v2-charges-id-capture
      responses:
        '200':
          description: La petición fue exitosa.
      description: 'Esta operación permite capturar una transacción que se encuentra en estado "Autorizada", es decir que aún no ha sido capturada. Esta operación es la segunda mitad del flujo de pagos en dos pasos (autorización y captura) que sucede cuando creas un cargo con el parámetro de captura falso. Una vez que captures un cargo, empezará el proceso de transferencia de esa transacción a tu cuenta bancaria. En el caso que no captures un cargo en un periodo de 4 días, el cargo vencerá y los fondos serán devueltos inmediatamente a la tarjeta de tu cliente y el estado del cargo cambiará a "Devuelta".'
      tags:
        - Cargos
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
  /v2/refunds:
    post:
      summary: Crear Devolución
      operationId: post-v2-refunds
      responses:
        '201':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    id: ref_live_TTfLAgaA8nz8PWbO
                    charge_id: chr_live_TWsfemI22ypplGK6
                    amount: 5000
                    reason: Devolución solicitada por el comercio
                    creation_date: 1487039706000
                    object: refund
                    metadata: {}
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada
          required: true
      description: |-
        Para crear una devolución es necesario que envíes el ID del cargo que deseas devolver. Esta operación retorna los fondos a la tarjeta de crédito o débito de tu cliente y adicionalmente las comisión variable cargada por Culqi.

        Opcionalmente podrías devolver solo una parte del cargo, operación conocida como devolución parcial. Puedes hacerlo las veces que quieras hasta que el monto total del cargo haya sido devuelto por completo.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  amount: 2000
                  charge_id: chr_live_7lYOtONQ9LxcgJUW
                  reason: fraudulento
              properties:
                amount:
                  type: integer
                  description: Monto de la devolución en céntimos.
                  example: 2000
                charge_id:
                  type: string
                  minLength: 1
                  description: ID del cargo a devolver.
                  example: chr_live_3xWxRF1Zswgp6C7N
                reason:
                  type: string
                  minLength: 1
                  description: 'Razón o motivo de la devolución, es una cadena de texto predefinida.'
                  enum:
                    - duplicado
                    - fraudulento
                    - solicitud_comprador
              required:
                - amount
                - charge_id
                - reason
      tags:
        - Devoluciones
    get:
      summary: Listar Devoluciones
      operationId: get-v2-refunds
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    data: []
                    paging:
                      previous: null
                      next: null
                      cursors:
                        before: null
                        after: null
      description: 'Listar devoluciones te permitirá obtener una serie de devoluciones existentes. De acuerdo a los filtros que uses, las devoluciones serán ordenados de acuerdo a su fecha de creación; siendo el primero el más reciente.'
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
        - schema:
            type: string
            example: '1476132639'
          in: query
          name: creation_date
          description: Fecha de la devolución en UNIX Timestamp
        - schema:
            type: string
            example: '1476132639'
          in: query
          name: creation_date_from
          description: Fecha inicial de las devoluciones en UNIX Timestamp
        - schema:
            type: string
            example: '1476132639'
          in: query
          name: creation_date_to
          description: Fecha limite de las devoluciones en UNIX Timestamp
        - schema:
            type: string
            enum:
              - duplicado
              - fraudulento
              - solicitud_comprador
          in: query
          name: reason
          description: 'Razón o motivo de la devolución, es una cadena de texto predefinida.'
        - schema:
            type: string
            example: '50'
            minLength: 1
            maxLength: 100
          in: query
          name: limit
          description: Cantidad exacta de devoluciones que se quieren listar.
        - schema:
            type: string
            example: ref_live_7lYOtONQ9LxcgJUW
            minLength: 25
            maxLength: 25
          in: query
          name: before
          description: El ID de la devolución desde donde se quiere traer la página anterior. No inclusivo.
        - schema:
            type: string
            example: ref_live_7lYOtOMM6LxcgJUW
            minLength: 25
            maxLength: 25
          in: query
          name: after
          description: El ID de la devolución desde donde se quiere traer la siguiente página. No inclusivo.
      tags:
        - Devoluciones
  '/v2/refunds/{id}':
    parameters:
      - schema:
          type: string
          example: ref_live_LVNpj300apa78Pjq
          minLength: 25
          maxLength: 25
        name: id
        in: path
        required: true
        description: ID de la devolución a consultar.
    get:
      summary: Consultar Devolución
      tags:
        - Devoluciones
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    id: ref_live_TTfLAgaA8nz8PWbO
                    charge_id: chr_live_TWsfemI22ypplGK6
                    amount: 5000
                    reason: Devolución solicitada por el comercio
                    creation_date: 1487039706000
                    object: refund
                    metadata: {}
      operationId: get-v2-refunds-id
      description: Devuelve los detalles de una devolución en particular. Para la petición solo debes enviar el ID de la devolución que Culqi te devolvió a la hora de crear una Devolución.
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
    patch:
      summary: Actualizar Devolución
      operationId: patch-v2-refunds-id
      responses:
        '200':
          description: La petición fue exitosa.
      tags:
        - Devoluciones
      description: Actualizar una devolución te permitirá agregar o reemplazar información a los valores de la metadata que enviaste a la hora de crear una devolución. Cualquier parámetro o valor no provisto será omitido en la el valores de la metadata.
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  metadata:
                    dni: '71702323'
              properties:
                metadata:
                  type: object
                  example:
                    dni: '71702323'
              required:
                - metadata
            examples:
              example-1:
                value:
                  metadata:
                    dni: '71702323'
  /v2/customers:
    get:
      summary: Listar Clientes
      tags:
        - Clientes
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    data:
                      - ...
                    paging:
                      previous: 'https://api.culqi.com/v2/customers?limit=50&before=cus_live_ Psny4smwxpmEDooU'
                      next: 'https://api.culqi.com/v2/customers?limit=50&after=cus_live_Lz6Yf sm7QqCPIECW'
                      cursors:
                        before: cus_live_Psny4smwxpmEDooU
                        after: cus_live_Lz6Yfsm7QqCPIECW
      operationId: get-v2-customers
      description: 'Listar Clientes te permitirá obtener una serie de Customer existentes. De acuerdo a los filtros que uses, los clientes serán ordenados de acuerdo a su fecha de creación; siendo el primero el más reciente.'
      parameters:
        - schema:
            type: string
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
        - schema:
            type: string
            minLength: 2
            maxLength: 50
            example: Richard
          in: query
          name: first_name
          description: Nombre del cliente.
        - schema:
            type: string
            example: Hendricks
            minLength: 2
            maxLength: 50
          in: query
          name: last_name
          description: Apellido del cliente.
        - schema:
            type: string
            minLength: 5
            maxLength: 50
            example: richard@piedpiper.com
          in: query
          name: email
          description: Correo electrónico del cliente.
        - schema:
            type: string
            minLength: 5
            maxLength: 100
            example: San Francisco Bay
          in: query
          name: address
          description: Dirección física del cliente.
        - schema:
            type: string
            example: San Francisco
            minLength: 5
            maxLength: 15
          in: query
          name: address_city
          description: Ciudad del cliente.
        - schema:
            type: string
            example: '3383478'
            minLength: 5
            maxLength: 15
          in: query
          name: phone_number
          description: Teléfono del cliente.
        - schema:
            type: string
            example: PE
          in: query
          name: country_code
          description: 'Código del país, en formato ISO-3166 (Alfa 2).'
        - schema:
            type: string
            minLength: 1
            example: '50'
            maxLength: 100
          in: query
          name: limit
          description: Cantidad exacta de clientes que se quieren listar.
        - schema:
            type: string
            example: cus_live_7lYOtONQ9LxcgJUW
            minLength: 25
            maxLength: 25
          in: query
          name: before
          description: El ID del cliente desde donde se quiere traer los resultados anteriores. No inclusivo.
        - schema:
            type: string
            example: cus_live_7lYOtOMM6LxcgJUW
            minLength: 25
            maxLength: 25
          in: query
          name: after
          description: El ID del cliente desde donde se quiere traer los resultados siguientes. No inclusivo.
    post:
      summary: Crear Cliente
      operationId: crear-cliente
      responses:
        '201':
          description: La petición fue exitosa.
      description: Crea un cliente enviando los datos de tu cliente y más datos relacionados al mismo a través de los valores de metadata.
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  first_name: Richard
                  last_name: Hendricks
                  email: richard@piedpiper.com
                  address: San Francisco Bay Area
                  address_city: Palo Alto
                  country_code: US
                  phone_number: '6505434800'
              properties:
                address:
                  type: string
                  description: Dirección del cliente.
                  example: Av. Brasil 123
                  minLength: 2
                  maxLength: 50
                address_city:
                  type: string
                  description: Ciudad del cliente
                  minLength: 2
                  maxLength: 50
                  example: Lima
                country_code:
                  type: string
                  minLength: 1
                  description: Código ISO-3166-1 (Alfa 2) del país del cliente.
                  example: PE
                email:
                  type: string
                  description: Correo electrónico del cliente
                  minLength: 5
                  maxLength: 50
                  example: richard@piedpiper.com
                  format: email
                first_name:
                  type: string
                  description: Nombre del cliente.
                  example: Richard
                  minLength: 2
                  maxLength: 50
                last_name:
                  type: string
                  description: Apellido del cliente.
                  example: Hendricks
                  minLength: 2
                  maxLength: 50
                phone_number:
                  type: string
                  description: Teléfono del cliente.
                  example: '6505434800'
                  minLength: 5
                  maxLength: 15
                metadata:
                  type: object
                  description: Informacion adicional que se requiera enviar al crear el plan.
                  example:
                    codigo_alumno: 0001A
              required:
                - address
                - address_city
                - country_code
                - email
                - first_name
                - last_name
                - phone_number
            examples:
              example-1:
                value:
                  first_name: Richard
                  last_name: Hendricks
                  email: richard@piedpiper.com
                  address: San Francisco Bay Area
                  address_city: Palo Alto
                  country_code: US
                  phone_number: '6505434800'
      tags:
        - Clientes
  '/v2/customers/{id}':
    parameters:
      - schema:
          type: string
          minLength: 25
          maxLength: 25
          example: cus_live_QDO81GT6Zaseewkp
        name: id
        in: path
        required: true
        description: ID del cliente.
    get:
      summary: Consultar Cliente
      tags:
        - Clientes
      responses:
        '200':
          description: La petición fue exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    object: customer
                    id: cus_live_Lz6Yfsm7QqCPIECW
                    creation_date: 1487041774773
                    email: richard@piedpiper.com
                    antifraud_details:
                      country_code: US
                      first_name: Richard
                      last_name: Richard
                      address_city: Palo Alto
                      address: San Francisco Bay Area
                      email: null
                      phone: '6505434800'
                      object: client
      operationId: get-v2-customers-id
      description: Devuelve los detalles de un cliente en particular. En la petición solo debes enviar el ID del cliente que Culqi te devolvió a la hora de crear uno.
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
    patch:
      summary: Actualizar Cliente
      operationId: patch-v2-customers-id
      responses:
        '200':
          description: OK
      description: Actualizar un cliente te permitirá modificar los valores enviados a la hora de crearlo. Cualquier parámetro que no sea proveído en la petición mantendrá el valor de la creación.
      parameters:
        - schema:
            type: string
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          required: true
          description: Llave privada.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  metadata:
                    dni: '71702323'
          application/xml:
            schema:
              description: ''
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    dni:
                      type: string
                      minLength: 1
                  required:
                    - dni
              required:
                - metadata
              x-examples:
                example-1:
                  metadata:
                    dni: '71702323'
        description: ''
      tags:
        - Clientes
    delete:
      summary: Eliminar Cliente
      operationId: delete-v2-customers-id
      responses:
        '200':
          description: Petición exitosa.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    id: cus_live_LbB0x6yB2Pd0JJnP
                    deleted: true
                    merchant_message: Se eliminó el cliente con ID cus_live_LbB0x6yB2Pd0JJnP exitosamente.
      description: Elimina de manera permanente a un cliente. Esta operación cancela cualquier cargo posterior o suscripción que esté relacionada con el Cliente.
      parameters:
        - schema:
            type: string
          in: header
          name: Content-type
          required: true
        - schema:
            type: string
            example: Bearer sk_test_UTCQSGcXW8bCyU59
          in: header
          name: Authorization
          description: Llave privada.
          required: true
      tags:
        - Clientes
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
